### ISSUE TITLE
用MikTex2.9编译readme.tex报错

### ISSUE THREAD

**Issue by 605527108** [CasperVector/biblatex-caspervector#2]
This is XeTeX, Version 3.14159265-2.6-0.99992 (MiKTeX 2.9)
entering extended mode
(readme.tex
LaTeX2e <2015/10/01> patch level 2
Babel <3.9n> and hyphenation patterns for 69 languages loaded.

("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\ctex\ctexart.
cls"
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\l3kernel\expl
3.sty"
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\l3kernel\expl
3-code.tex")
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\l3kernel\l3xd
vipdfmx.def"))
Document Class: ctexart 2016/02/02 v2.3 Chinese adapter for class article (CTEX
)

("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\l3packages\xp
arse\xparse.sty")
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\l3packages\l3
keys2e\l3keys2e.sty")
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\ctex\ctexhook
.sty")
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\ctex\ctexpatc
h.sty")
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\base\fix-cm.s
ty"
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\base\ts1enc.d
ef"))
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\ms\everysel.s
ty")
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\ctex\config\c
texopts.cfg")
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\base\article.
cls"
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class

("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\base\size10.c
lo"))
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\ctex\engine\c
tex-engine-xetex.def"
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\xelatex\xecjk\xeCJK
.sty"
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\l3packages\xt
emplate\xtemplate.sty")
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\fontspec\font
spec.sty"
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\fontspec\font
spec-patches.sty")
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\fontspec\font
spec-xetex.sty"
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\base\fontenc.
sty"
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\euenc\eu1enc.
def")
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\euenc\eu1lmr.
fd"))
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\xelatex\xunicode\xu
nicode.sty"
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\tipa\t3enc.de
f"
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\euenc\eu1lmss
.fd"))
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\graphics\grap
hicx.sty"
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\graphics\keyv
al.sty")
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\graphics\grap
hics.sty"
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\graphics\trig
.sty")
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\00miktex\grap
hics.cfg")
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\xelatex\xetex-def\x
etex.def"
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\generic\oberdiek\in
fwarerr.sty")
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\generic\oberdiek\lt
xcmds.sty")))))
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\fontspec\font
spec.cfg")))
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\xelatex\xecjk\xunic
ode-addon.sty")
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\xelatex\xunicode\xu
nicode.sty"
**\* Reloading Xunicode for encoding 'EU1' ***
)
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\xelatex\xecjk\xunic
ode-extra.def")
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\xelatex\xecjk\xeCJK
.cfg"))
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\xelatex\xecjk\xeCJK
fntef.sty"
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\ulem\ulem.sty
")
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\environ\envir
on.sty"
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\trimspaces\tr
imspaces.sty"))
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\cjk\CJKfntef.
sty")))
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\zhnumber\zhnu
mber.sty"
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\zhnumber\zhnu
mber-utf8.cfg"))
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\ctex\scheme\c
tex-scheme-chinese-article.def"
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\ctex\config\c
tex-name-utf8.cfg"))
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\ctex\ctex-c5s
ize.clo")
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\ctex\fontset\
ctex-fontset-windows.def"
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\ctex\fontset\
ctex-fontset-windowsnew.def")))
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\ctex\config\c
tex.cfg")
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\geometry\geom
etry.sty"
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\generic\oberdiek\if
pdf.sty")
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\generic\oberdiek\if
vtex.sty")
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\generic\ifxetex\ifx
etex.sty")
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\xelatex\xetexconfig
\geometry.cfg"))
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\biblatex\bibl
atex.sty"
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\biblatex\bibl
atex_.sty"
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\etoolbox\etoo
lbox.sty")
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\oberdiek\kvop
tions.sty"
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\generic\oberdiek\kv
setkeys.sty"
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\generic\oberdiek\et
excmds.sty"
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\generic\oberdiek\if
luatex.sty"))))
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\logreq\logreq
.sty"
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\logreq\logreq
.def"))
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\base\ifthen.s
ty")
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\url\url.sty")

("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\biblatex\blx-
dm.def")
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\biblatex\blx-
compat.def")
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\biblatex\bibl
atex_.def")
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\biblatex-casp
ervector\caspervector.bbx"
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\biblatex\bbx\
numeric.bbx"
("C:\Users\nklibmovie\AppData\Local\Programs\MiKTeX 2.9\tex\latex\biblatex\bbx\
standard.bbx"))
! Illegal parameter number in definition of \blx@defformat@d.
<to be read again> 
                   4
l.82 ^^I\usebibmacro{name:first-last}{#1}{#4
                                            }{#5}{#7}%
? 
请问你用的什么编译成功呢？

**Comment by CasperVector** [comment]
请参考 b121256c 中的解决方案。
