### ISSUE TITLE
英文参考文献作者多于三个时的显示问题

### ISSUE THREAD

**Issue by shengbinmeng** [CasperVector/biblatex-caspervector#3]
学校规定只显示前三个作者，后加et al.；目前的格式是只显示第一个作者，后加et al.。这是有意的还是需改正的？

**Comment by shengbinmeng** [comment]
这个问题可以通过设置biblatex的minnames选项解决：
`\usepackage[backend = biber, style = caspervector, utf8, sorting = none, minnames=3]{biblatex}`。

而且似乎中文文献作者不受此影响。

**Comment by CasperVector** [comment]
既然是学校要求，那我就改成默认这样好了，之前肯定是没注意到。
不过“中文文献作者不受此影响”是什么意思？我这里加了 `maxnames` 选项之后中西文文献作者数都变了。

**Comment by shengbinmeng** [comment]
我昨天没好好测中文文献，所以不确定。当时中文作者直接写的是“作者甲，作者乙，作者丙，作者丁”，所以加没加minnames选项都是一样（应该是被当成一个作者了）。刚才换成“作者甲 and 作者乙 and 作者丙 and 作者丁”后发现是会受影响的。不过排版出来是“作者甲，作者乙，作者丙,等。”，里面的英文逗号也是个issue吧，不知道最新版修正没。

**Comment by CasperVector** [comment]
那就没问题了。英文逗号的问题已处理，只是 commit 还在本地，未 push 到网上。

**Comment by zhangkmsjtu** [comment]
找了好久终于找到解决办法了。

可是我看不懂。到底怎么弄才能实现三个作者的问题？

**Comment by CasperVector** [comment]
你的 biblatex-caspervector 是什么版本？（可在编译时产生的 log 里看……）

**Comment by zhangkmsjtu** [comment]
搞好了
解决：下载了最新版biblatex-caspervector ，替换掉了原版的

**Comment by CasperVector** [comment]
好吧 @@
