### ISSUE TITLE
使用caspervector样式后，参考文献编号全是零

### ISSUE THREAD

**Issue by Milkysilk** [CasperVector/biblatex-caspervector#5]
环境：
biber version: 2.13
biblatex-caspervector是目前最新版

biblatex参数：
```tex
\usepackage[style = caspervector, backend = biber, utf8, sorting = cenyt]{biblatex}
```

编译步骤：
xelatex latex
biber -l zh__pinyin latex
xelatex latex
xelatex latex

生成的pdf文件截图：
![2020-01-12_23-10](https://user-images.githubusercontent.com/31210021/72220924-cd0d8700-3590-11ea-9011-2c0f96875978.png)

详细描述：使用了hyperref包，点击引用可以跳转到对应的文献，但文献前面的编号全都是0

**Comment by CasperVector** [comment]
新建一临时目录，在其中把下列代码存成 `test.tex`，然后执行 `latexmk -xelatex`，看结果怎样：
```tex
\documentclass{article}
\usepackage[backend = biber]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{glashow, weinberg}
\printbibliography
\end{document}
```

**Comment by Milkysilk** [comment]
终端打印：
https://gist.github.com/dsfjakdsggfdsg/454f62144fd315df2bea13ff7bf6e580

生成的pdf：
![2020-01-14_09-33](https://user-images.githubusercontent.com/31210021/72306097-f58ca280-36b0-11ea-8c83-db0432abb9f3.png)

**Comment by CasperVector** [comment]
那改成下面的代码再试试：
```tex
\documentclass[UTF8]{ctexart}
\usepackage[backend = biber, style = caspervector, utf8]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
\cite{glashow, weinberg}
\printbibliography
\end{document}
```

**Comment by Milkysilk** [comment]
> 那改成下面的代码再试试：
> 
> ```
> \documentclass[UTF8]{ctexart}
> \usepackage[backend = biber, style = caspervector, utf8]{biblatex}
> \addbibresource{biblatex-examples.bib}
> 
> \begin{document}
> \cite{glashow, weinberg}
> \printbibliography
> \end{document}
> ```

![2020-01-14_09-59](https://user-images.githubusercontent.com/31210021/72307271-bceec800-36b4-11ea-9a08-c460f976e1bd.png)

**Comment by CasperVector** [comment]
或许是你编译的产生的某些临时文件造成了问题。删掉临时文件重新编译试试？

**Comment by Milkysilk** [comment]
> 或许是你编译的产生的某些临时文件造成了问题。删掉临时文件重新编译试试？

试过，编号还是全0

在我机器上可以这样复现：
```bash
git clone https://github.com/Milkysilk/learning-latex.git
cd learning-latex/p14-references-and-biblatex
sed -i "19s/\\\\usepackage/% \\\\usepackage/g" latex.tex  # 先注释掉numeric 
sed -i "20s/% \\\\usepackage/\\\\usepackage/g" latex.tex  # 启用caspervector样式
rm -rf latex.pdf
latexmk -xelatex
```
其中的五个文件`blx-caspervector-base.def`，`blx-caspervector-gbk.def`，`blx-caspervector-utf8.def`，`caspervector.bbx`，`caspervector.cbx`来自 https://github.com/CasperVector/biblatex-caspervector 的最新提交

**Comment by CasperVector** [comment]
你用到的 `latex.tex` 里引用了 `biblatex` 这个条目，但 `test.bib` 里没有定义它。

**Comment by Milkysilk** [comment]
原来如此，十分感谢
因为使用numeric样式时，引用未定义文献不会编号全零，所以没有意识到这一点
